apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/qixiang/mintmaker/config/default?ref=32d920e533616a7c92e654aabfc23ca9c8e91c5b

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/qixiang/mintmaker
    newTag: f43171eb34ddc86814b46ca54185b14a1865c075

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

    #components:
    #  - ../components/rh-certs
